### ISSUE TITLE
pluggy.manager.PluginValidationError: Plugin 'pytest_pyodide_hook' for hook 'pytest_pycollect_makemodule'

### ISSUE THREAD

**Issue by miohtama** [pyodide/pytest-pyodide#34]
I am attempting to set up pyodide tests for an existing Python package.

I have created a simple test file based on the example:

```python
from pytest_pyodide import run_in_pyodide
@run_in_pyodide
def test_add(selenium):
    assert 1 + 1 == 2
```

I set up `dist` as per README.

However when I run

```shell
pytest --dist-dir=./dist/ -k pyodide
```

I am getting

```
Traceback (most recent call last):
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/trading-strategy-iVx-hmFV-py3.10/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/trading-strategy-iVx-hmFV-py3.10/lib/python3.10/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/trading-strategy-iVx-hmFV-py3.10/lib/python3.10/site-packages/_pytest/config/__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/trading-strategy-iVx-hmFV-py3.10/lib/python3.10/site-packages/_pytest/config/__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/trading-strategy-iVx-hmFV-py3.10/lib/python3.10/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/trading-strategy-iVx-hmFV-py3.10/lib/python3.10/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/trading-strategy-iVx-hmFV-py3.10/lib/python3.10/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/trading-strategy-iVx-hmFV-py3.10/lib/python3.10/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/trading-strategy-iVx-hmFV-py3.10/lib/python3.10/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/trading-strategy-iVx-hmFV-py3.10/lib/python3.10/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/trading-strategy-iVx-hmFV-py3.10/lib/python3.10/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/trading-strategy-iVx-hmFV-py3.10/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/trading-strategy-iVx-hmFV-py3.10/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/trading-strategy-iVx-hmFV-py3.10/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1172, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/trading-strategy-iVx-hmFV-py3.10/lib/python3.10/site-packages/pluggy/manager.py", line 300, in load_setuptools_entrypoints
    self.register(plugin, name=ep.name)
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/trading-strategy-iVx-hmFV-py3.10/lib/python3.10/site-packages/_pytest/config/__init__.py", line 436, in register
    ret: Optional[str] = super().register(plugin, name)
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/trading-strategy-iVx-hmFV-py3.10/lib/python3.10/site-packages/pluggy/manager.py", line 126, in register
    self._verify_hook(hook, hookimpl)
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/trading-strategy-iVx-hmFV-py3.10/lib/python3.10/site-packages/pluggy/manager.py", line 252, in _verify_hook
    raise PluginValidationError(
pluggy.manager.PluginValidationError: Plugin 'pytest_pyodide_hook' for hook 'pytest_pycollect_makemodule'
hookimpl definition: pytest_pycollect_makemodule(module_path: pathlib.Path, path: Any, parent: Any) -> None
Argument(s) {'module_path'} are declared in the hookimpl but can not be found in the hookspec
```

I am not sure if this error is related to my environment or a bug in pytest-pyodide and have no idea where to start poke in.

Packages:

```
poetry show|grep -i pyodide
pyodide-tblib                 1.7.1     Traceback serialization library.
pytest-pyodide                0.22.2    "Pytest plugin for testing applications that use Pyodide"

```

**Comment by hoodmane** [comment]
Perhaps it's a pytest or pluggy version mismatch? What versions of those do you have?

Also I don't really think `pytest-pyodide` is that useful outside of the Pyodide test suite, because you have to write dedicated tests for Pyodide. If you already have tests outside of Pyodide (or are thinking of making them) it's better to reuse those.

**Comment by miohtama** [comment]
@hoodmane Thank you for solving the problem. This fixed it for me:

```
 • Updating pytest (6.2.5 -> 7.1.3)
```

I am writing Pyodide-specific tests, as I want to have Python library functionality that can run in a browser and still make HTTP requests. Currently, I am using `requests` but I need to add a special path for Pyodide for this.

**Comment by hoodmane** [comment]
>  that can run in a browser and still make HTTP requests

If the interface is the same, then I still don't recommend `pytest-pyodide`. Suppose you have as part of your normal test suite:
```py
@pytest.mark.asyncio
async def test_http_request():
    result = await my_library.some_function_that_makes_a_request()
    assert result == "expected result"
```
and the expected behavior is that the same thing happens in Pyodide. Then you can just run your entire test suite in Pyodide and you don't need `pytest-pyodide` at all. To be honest, I would discourage usage of `pytest-pyodide` in almost all cases in favor of a selenium test that does something like:
```py
const py = await loadPyodide();
await py.loadPackage(["micropip", "pytest"]);
const micropip = py.pyimport("micropip");
await micropip.install("https://url/to/wheel_to_test.whl[tests]");
const pytest = py.pyimport("pytest");
# Run test suite
pytest.main(pyodide.toPy(["path/to/package_to_test"]));
```
Maybe @rth or @ryanking13 has a different opinion though.

**Comment by rth** [comment]
Agreed that running the full test suite is preferable. Though I think having some of the selenium and/or playwright fixtures for different browsers that work well with Pyodide is also a goal for this package. Otherwise, people would spend time re-implementing something like `_BrowserBaseRunner` and other derived classes.

**Comment by ryanking13** [comment]
My opinion is the same with Roman. I think the primary use case of pytest-pyodide is to be used for pyodide-based packages like [matplotlib-pyodide](https://github.com/pyodide/matplotlib-pyodide), [pyodide-importer](https://github.com/ryanking13/pyodide-importer), or [pyodide-http](https://github.com/koenvo/pyodide-http). But it is okay to use if for other Python packages.
